test-netlink-policy: Fix missing field initializer warnings on older GCC.
For some reason GCC 4.8 doesn't like this style of initialization,
complaining that nla_type is missing in the initializer:

  tests/test-netlink-policy.c: In function 'test_nl_policy_parse_ll_addr':
  tests/test-netlink-policy.c:60:9:
    error: missing initializer for field 'nla_type' of 'struct nlattr'
    [-Werror=missing-field-initializers]
         .nlattr.nla_type = TEST_POLICY_ATTR,
         ^
Let's use a normal designated initializer for the nested structure
to avoid this issue.

Fixes: 2f2ae5b6bdef ("tests: Fix endianness in netlink policy test fixtures.")
Signed-off-by: Ilya Maximets <i.maximets@ovn.org>